name: Docker Deploy

on:
  push:
    branches:
      - master
  release:
    types:
      - published


permissions: {}
jobs:
  docker:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
      - name: Login to DockerHub
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            tiangolo/issue-manager:latest
            ghcr.io/tiangolo/issue-manager:latest
          file: base.dockerfile
      - name: Build and push tag
        if: github.event_name == 'release'
        uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            tiangolo/issue-manager:${{ github.event.release.tag_name }}
            ghcr.io/tiangolo/issue-manager:${{ github.event.release.tag_name }}
          file: base.dockerfile
